--SQLQuery0-CREATE DATEBASE.sql

--CREATE DATABASE PV_521_DDL
--ON
--(
--	NAME		=	PV_521_DDL,
--	FILENAME	=	'E:\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PV_521_DML.mdf',
--	SIZE		=	8 MB,
--	MAXSIZE		=	500 MB,
--	FILEGROWTH  =	8 MB
--)
--LOG ON
--(
--	NAME		=	PV_521_DDL_log,
--	FILENAME	=	'E:\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PV_521_DML.ldf',
--	SIZE		=	8 MB,
--	MAXSIZE		=	500 MB,
--	FILEGROWTH  =	8 MB
--)

DROP DATABASE PV_521_DDL;